# Generated by Django 4.2.2 on 2023-07-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_category_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Section',
        ),
    ]
