# Generated by Django 4.2.2 on 2023-07-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_categories_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='category',
            new_name='section',
        ),
    ]
